name: vidflux
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  rxdart: ^0.23.1
  screen: ^0.0.5
  video_player: ^0.10.8+1  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
